import { MdDashboard } from 'react-icons/md';
import { FaUsers, FaTumblr, FaMoneyBillWaveAlt, FaUserTie } from 'react-icons/fa';
import { MdEventAvailable, MdOutlineRestaurantMenu,MdOutlineSubscriptions,MdFastfood,MdRestaurantMenu} from 'react-icons/md';
import { HiOutlineSpeakerphone } from 'react-icons/hi';
import { GiForkKnifeSpoon,GiBackwardTime } from 'react-icons/gi';
import { IoMdBowtie } from 'react-icons/io';
import { AiOutlinePullRequest } from 'react-icons/ai';
import { RiMessage2Fill, RiContactsBook2Line } from 'react-icons/ri';



export const CHILD_MENU = [
	
]

export const PRIMARY_MENU = [
	{
		id: 1,
		name: 'Dashboard',
		link: '/dashboard',
		prefix: true,
		accessor: [1,2],
		icon: <MdDashboard />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 2,
		name: 'Total Clubs',
		link: '/club',
		prefix: true,
		accessor: [1],
		icon: <MdOutlineRestaurantMenu />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 3,
		name: 'Earnings',
		link: '/earnings',
		prefix: true,
		accessor: [1,2],
		icon: <FaMoneyBillWaveAlt />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 4,
		name: 'Events',
		link: '/events',
		prefix: true,
		accessor: [2,3],
		icon: <MdEventAvailable />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 5,
		name: 'Promotions',
		link: '/promotions',
		prefix: true,
		accessor: [1,2],
		icon: <HiOutlineSpeakerphone />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 6,
		name: 'Promotions History',
		link: '/promotions-history',
		prefix: true,
		accessor: [1],
		icon: <GiBackwardTime />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 7,
		name: 'Subscriptions',
		link: '#',
		prefix: true,
		accessor: [1],
		icon: <MdOutlineSubscriptions />,
		iconClass: '',
		hasChild: true,
		activeLink: false,
		childMenus : [
						{
							id: 1,
							name: 'Plans',
							link: '/plan',
							prefix: true,
							accessor: [1],
							icon: '',
							iconClass: '',
							parent: 7,
							activeLink: false,
						},
						{
							id: 2,
							name: 'Features',
							link: '/feature',
							prefix: true,
							accessor: [1],
							icon: '',
							iconClass: '',
							parent: 7,
							activeLink: false,
						}
					],
	},
	{
		id: 8,
		name: 'Requests',
		link: '/request',
		prefix: true,
		accessor: [1],
		icon: <AiOutlinePullRequest />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 9,
		name: 'Menu',
		link: '/menu',
		prefix: true,
		accessor: [2],
		icon: <MdOutlineRestaurantMenu />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 10,
		name: 'Staff',
		link: '/staff',
		prefix: true,
		accessor: [2],
		icon: <IoMdBowtie />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 11,
		name: 'Manager',
		link: '/manager',
		prefix: true,
		accessor: [2],
		icon: <FaUserTie />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 12,
		name: 'Queries',
		link: '/queries',
		prefix: true,
		accessor: [1,2],
		icon: <RiMessage2Fill />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 13,
		name: 'Contact FOMO',
		link: '/contact',
		prefix: true,
		accessor: [2],
		icon: <RiContactsBook2Line />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 14,
		name: 'Orders',
		link: '/orders',
		prefix: true,
		accessor: [3],
		icon: <MdFastfood />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 15,
		name: 'Menu',
		link: '/menu',
		prefix: true,
		accessor: [3],
		icon: <MdRestaurantMenu />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
	{
		id: 16,
		name: 'Staff',
		link: '/staff',
		prefix: true,
		accessor: [3],
		icon: <IoMdBowtie />,
		iconClass: '',
		hasChild: false,
		activeLink: false,
	},
];
